// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: gRPC/service.proto

package chatv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageStatus int32

const (
	MessageStatus_MESSAGE_STATUS_UNSPECIFIED MessageStatus = 0
	MessageStatus_MESSAGE_STATUS_SENT        MessageStatus = 1
	MessageStatus_MESSAGE_STATUS_DELIVERED   MessageStatus = 2
	MessageStatus_MESSAGE_STATUS_READ        MessageStatus = 3
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "MESSAGE_STATUS_UNSPECIFIED",
		1: "MESSAGE_STATUS_SENT",
		2: "MESSAGE_STATUS_DELIVERED",
		3: "MESSAGE_STATUS_READ",
	}
	MessageStatus_value = map[string]int32{
		"MESSAGE_STATUS_UNSPECIFIED": 0,
		"MESSAGE_STATUS_SENT":        1,
		"MESSAGE_STATUS_DELIVERED":   2,
		"MESSAGE_STATUS_READ":        3,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gRPC_service_proto_enumTypes[0].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_gRPC_service_proto_enumTypes[0]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{0}
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User1Id       string                 `protobuf:"bytes,2,opt,name=user1_id,json=user1Id,proto3" json:"user1_id,omitempty"`
	User2Id       string                 `protobuf:"bytes,3,opt,name=user2_id,json=user2Id,proto3" json:"user2_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_gRPC_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{0}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetUser1Id() string {
	if x != nil {
		return x.User1Id
	}
	return ""
}

func (x *Chat) GetUser2Id() string {
	if x != nil {
		return x.User2Id
	}
	return ""
}

func (x *Chat) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Message id unique inside chat.
	ChatId        string                 `protobuf:"bytes,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderUserId  string                 `protobuf:"bytes,3,opt,name=sender_user_id,json=senderUserId,proto3" json:"sender_user_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Status        MessageStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=chat.v1.MessageStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_gRPC_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Message) GetSenderUserId() string {
	if x != nil {
		return x.SenderUserId
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateDirectChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User1Id       string                 `protobuf:"bytes,1,opt,name=user1_id,json=user1Id,proto3" json:"user1_id,omitempty"`
	User2Id       string                 `protobuf:"bytes,2,opt,name=user2_id,json=user2Id,proto3" json:"user2_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectChatRequest) Reset() {
	*x = CreateDirectChatRequest{}
	mi := &file_gRPC_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectChatRequest) ProtoMessage() {}

func (x *CreateDirectChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectChatRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectChatRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDirectChatRequest) GetUser1Id() string {
	if x != nil {
		return x.User1Id
	}
	return ""
}

func (x *CreateDirectChatRequest) GetUser2Id() string {
	if x != nil {
		return x.User2Id
	}
	return ""
}

type CreateDirectChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *Chat                  `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectChatResponse) Reset() {
	*x = CreateDirectChatResponse{}
	mi := &file_gRPC_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectChatResponse) ProtoMessage() {}

func (x *CreateDirectChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectChatResponse.ProtoReflect.Descriptor instead.
func (*CreateDirectChatResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDirectChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

type DeleteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_gRPC_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type DeleteChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatResponse) Reset() {
	*x = DeleteChatResponse{}
	mi := &file_gRPC_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatResponse) ProtoMessage() {}

func (x *DeleteChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatResponse.ProtoReflect.Descriptor instead.
func (*DeleteChatResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{5}
}

type CreateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderUserId  string                 `protobuf:"bytes,2,opt,name=sender_user_id,json=senderUserId,proto3" json:"sender_user_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageRequest) Reset() {
	*x = CreateMessageRequest{}
	mi := &file_gRPC_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageRequest) ProtoMessage() {}

func (x *CreateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageRequest.ProtoReflect.Descriptor instead.
func (*CreateMessageRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *CreateMessageRequest) GetSenderUserId() string {
	if x != nil {
		return x.SenderUserId
	}
	return ""
}

func (x *CreateMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CreateMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageResponse) Reset() {
	*x = CreateMessageResponse{}
	mi := &file_gRPC_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageResponse) ProtoMessage() {}

func (x *CreateMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageResponse.ProtoReflect.Descriptor instead.
func (*CreateMessageResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendMessageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChatId          string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderUserId    string                 `protobuf:"bytes,2,opt,name=sender_user_id,json=senderUserId,proto3" json:"sender_user_id,omitempty"`
	Text            string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	ClientMessageId string                 `protobuf:"bytes,4,opt,name=client_message_id,json=clientMessageId,proto3" json:"client_message_id,omitempty"` // Optional idempotency key from client.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_gRPC_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMessageRequest) GetSenderUserId() string {
	if x != nil {
		return x.SenderUserId
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendMessageRequest) GetClientMessageId() string {
	if x != nil {
		return x.ClientMessageId
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_gRPC_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type UpdateMessageStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        MessageStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=chat.v1.MessageStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageStatusRequest) Reset() {
	*x = UpdateMessageStatusRequest{}
	mi := &file_gRPC_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageStatusRequest) ProtoMessage() {}

func (x *UpdateMessageStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateMessageStatusRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateMessageStatusRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *UpdateMessageStatusRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *UpdateMessageStatusRequest) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_MESSAGE_STATUS_UNSPECIFIED
}

type UpdateMessageStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageStatusResponse) Reset() {
	*x = UpdateMessageStatusResponse{}
	mi := &file_gRPC_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageStatusResponse) ProtoMessage() {}

func (x *UpdateMessageStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateMessageStatusResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateMessageStatusResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type GetChatPreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatPreviewRequest) Reset() {
	*x = GetChatPreviewRequest{}
	mi := &file_gRPC_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatPreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatPreviewRequest) ProtoMessage() {}

func (x *GetChatPreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatPreviewRequest.ProtoReflect.Descriptor instead.
func (*GetChatPreviewRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetChatPreviewRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type ChatPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	OtherUserId   string                 `protobuf:"bytes,2,opt,name=other_user_id,json=otherUserId,proto3" json:"other_user_id,omitempty"` // The other participant in this direct chat.
	LastMessage   *Message               `protobuf:"bytes,3,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	LastMessageAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_message_at,json=lastMessageAt,proto3" json:"last_message_at,omitempty"`
	UnreadCount   int64                  `protobuf:"varint,5,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatPreview) Reset() {
	*x = ChatPreview{}
	mi := &file_gRPC_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPreview) ProtoMessage() {}

func (x *ChatPreview) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPreview.ProtoReflect.Descriptor instead.
func (*ChatPreview) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{13}
}

func (x *ChatPreview) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatPreview) GetOtherUserId() string {
	if x != nil {
		return x.OtherUserId
	}
	return ""
}

func (x *ChatPreview) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *ChatPreview) GetLastMessageAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageAt
	}
	return nil
}

func (x *ChatPreview) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type GetChatPreviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Preview       *ChatPreview           `protobuf:"bytes,1,opt,name=preview,proto3" json:"preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatPreviewResponse) Reset() {
	*x = GetChatPreviewResponse{}
	mi := &file_gRPC_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatPreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatPreviewResponse) ProtoMessage() {}

func (x *GetChatPreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatPreviewResponse.ProtoReflect.Descriptor instead.
func (*GetChatPreviewResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetChatPreviewResponse) GetPreview() *ChatPreview {
	if x != nil {
		return x.Preview
	}
	return nil
}

type GetLastMessagesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ChatId          string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Limit           int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                              // If zero, server uses default = 50.
	BeforeMessageId int64                  `protobuf:"varint,3,opt,name=before_message_id,json=beforeMessageId,proto3" json:"before_message_id,omitempty"` // If zero, server starts from the latest messages.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLastMessagesRequest) Reset() {
	*x = GetLastMessagesRequest{}
	mi := &file_gRPC_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastMessagesRequest) ProtoMessage() {}

func (x *GetLastMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetLastMessagesRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetLastMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GetLastMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLastMessagesRequest) GetBeforeMessageId() int64 {
	if x != nil {
		return x.BeforeMessageId
	}
	return 0
}

type GetLastMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastMessagesResponse) Reset() {
	*x = GetLastMessagesResponse{}
	mi := &file_gRPC_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastMessagesResponse) ProtoMessage() {}

func (x *GetLastMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetLastMessagesResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetLastMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetLastMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ListUserChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`   // If zero, server uses default = 15.
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"` // Simple pagination for MVP.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsRequest) Reset() {
	*x = ListUserChatsRequest{}
	mi := &file_gRPC_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsRequest) ProtoMessage() {}

func (x *ListUserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsRequest.ProtoReflect.Descriptor instead.
func (*ListUserChatsRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListUserChatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserChatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListUserChatsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListUserChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*ChatPreview         `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsResponse) Reset() {
	*x = ListUserChatsResponse{}
	mi := &file_gRPC_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsResponse) ProtoMessage() {}

func (x *ListUserChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsResponse.ProtoReflect.Descriptor instead.
func (*ListUserChatsResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{18}
}

func (x *ListUserChatsResponse) GetChats() []*ChatPreview {
	if x != nil {
		return x.Chats
	}
	return nil
}

type MarkChatReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UpToMessageId int64                  `protobuf:"varint,3,opt,name=up_to_message_id,json=upToMessageId,proto3" json:"up_to_message_id,omitempty"` // If zero, server marks up to the latest message.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkChatReadRequest) Reset() {
	*x = MarkChatReadRequest{}
	mi := &file_gRPC_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkChatReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkChatReadRequest) ProtoMessage() {}

func (x *MarkChatReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkChatReadRequest.ProtoReflect.Descriptor instead.
func (*MarkChatReadRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{19}
}

func (x *MarkChatReadRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *MarkChatReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarkChatReadRequest) GetUpToMessageId() int64 {
	if x != nil {
		return x.UpToMessageId
	}
	return 0
}

type MarkChatReadResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UpdatedMessages int64                  `protobuf:"varint,1,opt,name=updated_messages,json=updatedMessages,proto3" json:"updated_messages,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MarkChatReadResponse) Reset() {
	*x = MarkChatReadResponse{}
	mi := &file_gRPC_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkChatReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkChatReadResponse) ProtoMessage() {}

func (x *MarkChatReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkChatReadResponse.ProtoReflect.Descriptor instead.
func (*MarkChatReadResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_service_proto_rawDescGZIP(), []int{20}
}

func (x *MarkChatReadResponse) GetUpdatedMessages() int64 {
	if x != nil {
		return x.UpdatedMessages
	}
	return 0
}

var File_gRPC_service_proto protoreflect.FileDescriptor

const file_gRPC_service_proto_rawDesc = "" +
	"\n" +
	"\x12gRPC/service.proto\x12\achat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\buser1_id\x18\x02 \x01(\tR\auser1Id\x12\x19\n" +
	"\buser2_id\x18\x03 \x01(\tR\auser2Id\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x92\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\tR\x06chatId\x12$\n" +
	"\x0esender_user_id\x18\x03 \x01(\tR\fsenderUserId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.chat.v1.MessageStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"O\n" +
	"\x17CreateDirectChatRequest\x12\x19\n" +
	"\buser1_id\x18\x01 \x01(\tR\auser1Id\x12\x19\n" +
	"\buser2_id\x18\x02 \x01(\tR\auser2Id\"=\n" +
	"\x18CreateDirectChatResponse\x12!\n" +
	"\x04chat\x18\x01 \x01(\v2\r.chat.v1.ChatR\x04chat\",\n" +
	"\x11DeleteChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"\x14\n" +
	"\x12DeleteChatResponse\"i\n" +
	"\x14CreateMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12$\n" +
	"\x0esender_user_id\x18\x02 \x01(\tR\fsenderUserId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"C\n" +
	"\x15CreateMessageResponse\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.chat.v1.MessageR\amessage\"\x93\x01\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12$\n" +
	"\x0esender_user_id\x18\x02 \x01(\tR\fsenderUserId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12*\n" +
	"\x11client_message_id\x18\x04 \x01(\tR\x0fclientMessageId\"A\n" +
	"\x13SendMessageResponse\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.chat.v1.MessageR\amessage\"\x84\x01\n" +
	"\x1aUpdateMessageStatusRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.chat.v1.MessageStatusR\x06status\"I\n" +
	"\x1bUpdateMessageStatusResponse\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.chat.v1.MessageR\amessage\"0\n" +
	"\x15GetChatPreviewRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"\xe6\x01\n" +
	"\vChatPreview\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\"\n" +
	"\rother_user_id\x18\x02 \x01(\tR\votherUserId\x123\n" +
	"\flast_message\x18\x03 \x01(\v2\x10.chat.v1.MessageR\vlastMessage\x12B\n" +
	"\x0flast_message_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastMessageAt\x12!\n" +
	"\funread_count\x18\x05 \x01(\x03R\vunreadCount\"H\n" +
	"\x16GetChatPreviewResponse\x12.\n" +
	"\apreview\x18\x01 \x01(\v2\x14.chat.v1.ChatPreviewR\apreview\"s\n" +
	"\x16GetLastMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12*\n" +
	"\x11before_message_id\x18\x03 \x01(\x03R\x0fbeforeMessageId\"b\n" +
	"\x17GetLastMessagesResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.chat.v1.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"]\n" +
	"\x14ListUserChatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"C\n" +
	"\x15ListUserChatsResponse\x12*\n" +
	"\x05chats\x18\x01 \x03(\v2\x14.chat.v1.ChatPreviewR\x05chats\"p\n" +
	"\x13MarkChatReadRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x10up_to_message_id\x18\x03 \x01(\x03R\rupToMessageId\"A\n" +
	"\x14MarkChatReadResponse\x12)\n" +
	"\x10updated_messages\x18\x01 \x01(\x03R\x0fupdatedMessages*\x7f\n" +
	"\rMessageStatus\x12\x1e\n" +
	"\x1aMESSAGE_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MESSAGE_STATUS_SENT\x10\x01\x12\x1c\n" +
	"\x18MESSAGE_STATUS_DELIVERED\x10\x02\x12\x17\n" +
	"\x13MESSAGE_STATUS_READ\x10\x032\xf6\x05\n" +
	"\x12ChatMessageService\x12W\n" +
	"\x10CreateDirectChat\x12 .chat.v1.CreateDirectChatRequest\x1a!.chat.v1.CreateDirectChatResponse\x12E\n" +
	"\n" +
	"DeleteChat\x12\x1a.chat.v1.DeleteChatRequest\x1a\x1b.chat.v1.DeleteChatResponse\x12N\n" +
	"\rCreateMessage\x12\x1d.chat.v1.CreateMessageRequest\x1a\x1e.chat.v1.CreateMessageResponse\x12H\n" +
	"\vSendMessage\x12\x1b.chat.v1.SendMessageRequest\x1a\x1c.chat.v1.SendMessageResponse\x12`\n" +
	"\x13UpdateMessageStatus\x12#.chat.v1.UpdateMessageStatusRequest\x1a$.chat.v1.UpdateMessageStatusResponse\x12Q\n" +
	"\x0eGetChatPreview\x12\x1e.chat.v1.GetChatPreviewRequest\x1a\x1f.chat.v1.GetChatPreviewResponse\x12T\n" +
	"\x0fGetLastMessages\x12\x1f.chat.v1.GetLastMessagesRequest\x1a .chat.v1.GetLastMessagesResponse\x12N\n" +
	"\rListUserChats\x12\x1d.chat.v1.ListUserChatsRequest\x1a\x1e.chat.v1.ListUserChatsResponse\x12K\n" +
	"\fMarkChatRead\x12\x1c.chat.v1.MarkChatReadRequest\x1a\x1d.chat.v1.MarkChatReadResponseB;Z9gitlab.com/siffka/chat-message-mgz/pkg/api/chat/v1;chatv1b\x06proto3"

var (
	file_gRPC_service_proto_rawDescOnce sync.Once
	file_gRPC_service_proto_rawDescData []byte
)

func file_gRPC_service_proto_rawDescGZIP() []byte {
	file_gRPC_service_proto_rawDescOnce.Do(func() {
		file_gRPC_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gRPC_service_proto_rawDesc), len(file_gRPC_service_proto_rawDesc)))
	})
	return file_gRPC_service_proto_rawDescData
}

var file_gRPC_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gRPC_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_gRPC_service_proto_goTypes = []any{
	(MessageStatus)(0),                  // 0: chat.v1.MessageStatus
	(*Chat)(nil),                        // 1: chat.v1.Chat
	(*Message)(nil),                     // 2: chat.v1.Message
	(*CreateDirectChatRequest)(nil),     // 3: chat.v1.CreateDirectChatRequest
	(*CreateDirectChatResponse)(nil),    // 4: chat.v1.CreateDirectChatResponse
	(*DeleteChatRequest)(nil),           // 5: chat.v1.DeleteChatRequest
	(*DeleteChatResponse)(nil),          // 6: chat.v1.DeleteChatResponse
	(*CreateMessageRequest)(nil),        // 7: chat.v1.CreateMessageRequest
	(*CreateMessageResponse)(nil),       // 8: chat.v1.CreateMessageResponse
	(*SendMessageRequest)(nil),          // 9: chat.v1.SendMessageRequest
	(*SendMessageResponse)(nil),         // 10: chat.v1.SendMessageResponse
	(*UpdateMessageStatusRequest)(nil),  // 11: chat.v1.UpdateMessageStatusRequest
	(*UpdateMessageStatusResponse)(nil), // 12: chat.v1.UpdateMessageStatusResponse
	(*GetChatPreviewRequest)(nil),       // 13: chat.v1.GetChatPreviewRequest
	(*ChatPreview)(nil),                 // 14: chat.v1.ChatPreview
	(*GetChatPreviewResponse)(nil),      // 15: chat.v1.GetChatPreviewResponse
	(*GetLastMessagesRequest)(nil),      // 16: chat.v1.GetLastMessagesRequest
	(*GetLastMessagesResponse)(nil),     // 17: chat.v1.GetLastMessagesResponse
	(*ListUserChatsRequest)(nil),        // 18: chat.v1.ListUserChatsRequest
	(*ListUserChatsResponse)(nil),       // 19: chat.v1.ListUserChatsResponse
	(*MarkChatReadRequest)(nil),         // 20: chat.v1.MarkChatReadRequest
	(*MarkChatReadResponse)(nil),        // 21: chat.v1.MarkChatReadResponse
	(*timestamppb.Timestamp)(nil),       // 22: google.protobuf.Timestamp
}
var file_gRPC_service_proto_depIdxs = []int32{
	22, // 0: chat.v1.Chat.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: chat.v1.Message.status:type_name -> chat.v1.MessageStatus
	22, // 2: chat.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	22, // 3: chat.v1.Message.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: chat.v1.CreateDirectChatResponse.chat:type_name -> chat.v1.Chat
	2,  // 5: chat.v1.CreateMessageResponse.message:type_name -> chat.v1.Message
	2,  // 6: chat.v1.SendMessageResponse.message:type_name -> chat.v1.Message
	0,  // 7: chat.v1.UpdateMessageStatusRequest.status:type_name -> chat.v1.MessageStatus
	2,  // 8: chat.v1.UpdateMessageStatusResponse.message:type_name -> chat.v1.Message
	2,  // 9: chat.v1.ChatPreview.last_message:type_name -> chat.v1.Message
	22, // 10: chat.v1.ChatPreview.last_message_at:type_name -> google.protobuf.Timestamp
	14, // 11: chat.v1.GetChatPreviewResponse.preview:type_name -> chat.v1.ChatPreview
	2,  // 12: chat.v1.GetLastMessagesResponse.messages:type_name -> chat.v1.Message
	14, // 13: chat.v1.ListUserChatsResponse.chats:type_name -> chat.v1.ChatPreview
	3,  // 14: chat.v1.ChatMessageService.CreateDirectChat:input_type -> chat.v1.CreateDirectChatRequest
	5,  // 15: chat.v1.ChatMessageService.DeleteChat:input_type -> chat.v1.DeleteChatRequest
	7,  // 16: chat.v1.ChatMessageService.CreateMessage:input_type -> chat.v1.CreateMessageRequest
	9,  // 17: chat.v1.ChatMessageService.SendMessage:input_type -> chat.v1.SendMessageRequest
	11, // 18: chat.v1.ChatMessageService.UpdateMessageStatus:input_type -> chat.v1.UpdateMessageStatusRequest
	13, // 19: chat.v1.ChatMessageService.GetChatPreview:input_type -> chat.v1.GetChatPreviewRequest
	16, // 20: chat.v1.ChatMessageService.GetLastMessages:input_type -> chat.v1.GetLastMessagesRequest
	18, // 21: chat.v1.ChatMessageService.ListUserChats:input_type -> chat.v1.ListUserChatsRequest
	20, // 22: chat.v1.ChatMessageService.MarkChatRead:input_type -> chat.v1.MarkChatReadRequest
	4,  // 23: chat.v1.ChatMessageService.CreateDirectChat:output_type -> chat.v1.CreateDirectChatResponse
	6,  // 24: chat.v1.ChatMessageService.DeleteChat:output_type -> chat.v1.DeleteChatResponse
	8,  // 25: chat.v1.ChatMessageService.CreateMessage:output_type -> chat.v1.CreateMessageResponse
	10, // 26: chat.v1.ChatMessageService.SendMessage:output_type -> chat.v1.SendMessageResponse
	12, // 27: chat.v1.ChatMessageService.UpdateMessageStatus:output_type -> chat.v1.UpdateMessageStatusResponse
	15, // 28: chat.v1.ChatMessageService.GetChatPreview:output_type -> chat.v1.GetChatPreviewResponse
	17, // 29: chat.v1.ChatMessageService.GetLastMessages:output_type -> chat.v1.GetLastMessagesResponse
	19, // 30: chat.v1.ChatMessageService.ListUserChats:output_type -> chat.v1.ListUserChatsResponse
	21, // 31: chat.v1.ChatMessageService.MarkChatRead:output_type -> chat.v1.MarkChatReadResponse
	23, // [23:32] is the sub-list for method output_type
	14, // [14:23] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_gRPC_service_proto_init() }
func file_gRPC_service_proto_init() {
	if File_gRPC_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gRPC_service_proto_rawDesc), len(file_gRPC_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_service_proto_goTypes,
		DependencyIndexes: file_gRPC_service_proto_depIdxs,
		EnumInfos:         file_gRPC_service_proto_enumTypes,
		MessageInfos:      file_gRPC_service_proto_msgTypes,
	}.Build()
	File_gRPC_service_proto = out.File
	file_gRPC_service_proto_goTypes = nil
	file_gRPC_service_proto_depIdxs = nil
}
