// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: gRPC/service.proto

package chatv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatMessageService_CreateDirectChat_FullMethodName    = "/chat.v1.ChatMessageService/CreateDirectChat"
	ChatMessageService_DeleteChat_FullMethodName          = "/chat.v1.ChatMessageService/DeleteChat"
	ChatMessageService_CreateMessage_FullMethodName       = "/chat.v1.ChatMessageService/CreateMessage"
	ChatMessageService_SendMessage_FullMethodName         = "/chat.v1.ChatMessageService/SendMessage"
	ChatMessageService_UpdateMessageStatus_FullMethodName = "/chat.v1.ChatMessageService/UpdateMessageStatus"
	ChatMessageService_GetChatPreview_FullMethodName      = "/chat.v1.ChatMessageService/GetChatPreview"
	ChatMessageService_GetLastMessages_FullMethodName     = "/chat.v1.ChatMessageService/GetLastMessages"
	ChatMessageService_ListUserChats_FullMethodName       = "/chat.v1.ChatMessageService/ListUserChats"
	ChatMessageService_MarkChatRead_FullMethodName        = "/chat.v1.ChatMessageService/MarkChatRead"
)

// ChatMessageServiceClient is the client API for ChatMessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatMessageServiceClient interface {
	CreateDirectChat(ctx context.Context, in *CreateDirectChatRequest, opts ...grpc.CallOption) (*CreateDirectChatResponse, error)
	DeleteChat(ctx context.Context, in *DeleteChatRequest, opts ...grpc.CallOption) (*DeleteChatResponse, error)
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error)
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	UpdateMessageStatus(ctx context.Context, in *UpdateMessageStatusRequest, opts ...grpc.CallOption) (*UpdateMessageStatusResponse, error)
	GetChatPreview(ctx context.Context, in *GetChatPreviewRequest, opts ...grpc.CallOption) (*GetChatPreviewResponse, error)
	GetLastMessages(ctx context.Context, in *GetLastMessagesRequest, opts ...grpc.CallOption) (*GetLastMessagesResponse, error)
	ListUserChats(ctx context.Context, in *ListUserChatsRequest, opts ...grpc.CallOption) (*ListUserChatsResponse, error)
	MarkChatRead(ctx context.Context, in *MarkChatReadRequest, opts ...grpc.CallOption) (*MarkChatReadResponse, error)
}

type chatMessageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatMessageServiceClient(cc grpc.ClientConnInterface) ChatMessageServiceClient {
	return &chatMessageServiceClient{cc}
}

func (c *chatMessageServiceClient) CreateDirectChat(ctx context.Context, in *CreateDirectChatRequest, opts ...grpc.CallOption) (*CreateDirectChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDirectChatResponse)
	err := c.cc.Invoke(ctx, ChatMessageService_CreateDirectChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatMessageServiceClient) DeleteChat(ctx context.Context, in *DeleteChatRequest, opts ...grpc.CallOption) (*DeleteChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteChatResponse)
	err := c.cc.Invoke(ctx, ChatMessageService_DeleteChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatMessageServiceClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMessageResponse)
	err := c.cc.Invoke(ctx, ChatMessageService_CreateMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatMessageServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, ChatMessageService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatMessageServiceClient) UpdateMessageStatus(ctx context.Context, in *UpdateMessageStatusRequest, opts ...grpc.CallOption) (*UpdateMessageStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMessageStatusResponse)
	err := c.cc.Invoke(ctx, ChatMessageService_UpdateMessageStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatMessageServiceClient) GetChatPreview(ctx context.Context, in *GetChatPreviewRequest, opts ...grpc.CallOption) (*GetChatPreviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatPreviewResponse)
	err := c.cc.Invoke(ctx, ChatMessageService_GetChatPreview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatMessageServiceClient) GetLastMessages(ctx context.Context, in *GetLastMessagesRequest, opts ...grpc.CallOption) (*GetLastMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastMessagesResponse)
	err := c.cc.Invoke(ctx, ChatMessageService_GetLastMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatMessageServiceClient) ListUserChats(ctx context.Context, in *ListUserChatsRequest, opts ...grpc.CallOption) (*ListUserChatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserChatsResponse)
	err := c.cc.Invoke(ctx, ChatMessageService_ListUserChats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatMessageServiceClient) MarkChatRead(ctx context.Context, in *MarkChatReadRequest, opts ...grpc.CallOption) (*MarkChatReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkChatReadResponse)
	err := c.cc.Invoke(ctx, ChatMessageService_MarkChatRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatMessageServiceServer is the server API for ChatMessageService service.
// All implementations must embed UnimplementedChatMessageServiceServer
// for forward compatibility.
type ChatMessageServiceServer interface {
	CreateDirectChat(context.Context, *CreateDirectChatRequest) (*CreateDirectChatResponse, error)
	DeleteChat(context.Context, *DeleteChatRequest) (*DeleteChatResponse, error)
	CreateMessage(context.Context, *CreateMessageRequest) (*CreateMessageResponse, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	UpdateMessageStatus(context.Context, *UpdateMessageStatusRequest) (*UpdateMessageStatusResponse, error)
	GetChatPreview(context.Context, *GetChatPreviewRequest) (*GetChatPreviewResponse, error)
	GetLastMessages(context.Context, *GetLastMessagesRequest) (*GetLastMessagesResponse, error)
	ListUserChats(context.Context, *ListUserChatsRequest) (*ListUserChatsResponse, error)
	MarkChatRead(context.Context, *MarkChatReadRequest) (*MarkChatReadResponse, error)
	mustEmbedUnimplementedChatMessageServiceServer()
}

// UnimplementedChatMessageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatMessageServiceServer struct{}

func (UnimplementedChatMessageServiceServer) CreateDirectChat(context.Context, *CreateDirectChatRequest) (*CreateDirectChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDirectChat not implemented")
}
func (UnimplementedChatMessageServiceServer) DeleteChat(context.Context, *DeleteChatRequest) (*DeleteChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteChat not implemented")
}
func (UnimplementedChatMessageServiceServer) CreateMessage(context.Context, *CreateMessageRequest) (*CreateMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMessage not implemented")
}
func (UnimplementedChatMessageServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedChatMessageServiceServer) UpdateMessageStatus(context.Context, *UpdateMessageStatusRequest) (*UpdateMessageStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMessageStatus not implemented")
}
func (UnimplementedChatMessageServiceServer) GetChatPreview(context.Context, *GetChatPreviewRequest) (*GetChatPreviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatPreview not implemented")
}
func (UnimplementedChatMessageServiceServer) GetLastMessages(context.Context, *GetLastMessagesRequest) (*GetLastMessagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastMessages not implemented")
}
func (UnimplementedChatMessageServiceServer) ListUserChats(context.Context, *ListUserChatsRequest) (*ListUserChatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserChats not implemented")
}
func (UnimplementedChatMessageServiceServer) MarkChatRead(context.Context, *MarkChatReadRequest) (*MarkChatReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkChatRead not implemented")
}
func (UnimplementedChatMessageServiceServer) mustEmbedUnimplementedChatMessageServiceServer() {}
func (UnimplementedChatMessageServiceServer) testEmbeddedByValue()                            {}

// UnsafeChatMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatMessageServiceServer will
// result in compilation errors.
type UnsafeChatMessageServiceServer interface {
	mustEmbedUnimplementedChatMessageServiceServer()
}

func RegisterChatMessageServiceServer(s grpc.ServiceRegistrar, srv ChatMessageServiceServer) {
	// If the following call panics, it indicates UnimplementedChatMessageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatMessageService_ServiceDesc, srv)
}

func _ChatMessageService_CreateDirectChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDirectChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatMessageServiceServer).CreateDirectChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatMessageService_CreateDirectChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatMessageServiceServer).CreateDirectChat(ctx, req.(*CreateDirectChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatMessageService_DeleteChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatMessageServiceServer).DeleteChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatMessageService_DeleteChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatMessageServiceServer).DeleteChat(ctx, req.(*DeleteChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatMessageService_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatMessageServiceServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatMessageService_CreateMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatMessageServiceServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatMessageService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatMessageServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatMessageService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatMessageServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatMessageService_UpdateMessageStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMessageStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatMessageServiceServer).UpdateMessageStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatMessageService_UpdateMessageStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatMessageServiceServer).UpdateMessageStatus(ctx, req.(*UpdateMessageStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatMessageService_GetChatPreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatPreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatMessageServiceServer).GetChatPreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatMessageService_GetChatPreview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatMessageServiceServer).GetChatPreview(ctx, req.(*GetChatPreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatMessageService_GetLastMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatMessageServiceServer).GetLastMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatMessageService_GetLastMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatMessageServiceServer).GetLastMessages(ctx, req.(*GetLastMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatMessageService_ListUserChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserChatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatMessageServiceServer).ListUserChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatMessageService_ListUserChats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatMessageServiceServer).ListUserChats(ctx, req.(*ListUserChatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatMessageService_MarkChatRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkChatReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatMessageServiceServer).MarkChatRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatMessageService_MarkChatRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatMessageServiceServer).MarkChatRead(ctx, req.(*MarkChatReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatMessageService_ServiceDesc is the grpc.ServiceDesc for ChatMessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatMessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.v1.ChatMessageService",
	HandlerType: (*ChatMessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDirectChat",
			Handler:    _ChatMessageService_CreateDirectChat_Handler,
		},
		{
			MethodName: "DeleteChat",
			Handler:    _ChatMessageService_DeleteChat_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _ChatMessageService_CreateMessage_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ChatMessageService_SendMessage_Handler,
		},
		{
			MethodName: "UpdateMessageStatus",
			Handler:    _ChatMessageService_UpdateMessageStatus_Handler,
		},
		{
			MethodName: "GetChatPreview",
			Handler:    _ChatMessageService_GetChatPreview_Handler,
		},
		{
			MethodName: "GetLastMessages",
			Handler:    _ChatMessageService_GetLastMessages_Handler,
		},
		{
			MethodName: "ListUserChats",
			Handler:    _ChatMessageService_ListUserChats_Handler,
		},
		{
			MethodName: "MarkChatRead",
			Handler:    _ChatMessageService_MarkChatRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC/service.proto",
}
